apiVersion: apps/v1
kind: Deployment
metadata:
  name: covidapp-deployment
  labels:
    app: covidapp
spec:
  selector:
    matchLabels:
      app: covidapp
  replicas: 3
  template:
    metadata:
      labels:
        app: covidapp
    spec:
      containers:
      - name: covidapp
        image: localhost:32000/covidapp:registry
        ports:
        - containerPort: 443
